apps/servicos/urls.py
from django.urls import path

app_name = 'servicos'

from . import views

urlpatterns = [
    path('novo-servico/', views.novo_servico, name='novo_servico'),
    path('servicos/', views.lista_servicos, name='lista_servicos'),
    path('ordem-servicos/', views.lista_ordem_servico, name='lista_ordem_servico'),
    path('criar-ordem-servico/', views.criar_ordem_servico, name='criar_ordem_servico'),
    path('editar-servico/<int:pk>/', views.editar_servico, name='editar_servico'),
    path('editar-ordem-servico/<int:pk>/', views.editar_ordem_servico, name='editar_ordem_servico')
]

oficina/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('servicos/', include('servicos.urls', namespace='servicos')),
    path('', include('geral.urls', namespace='geral')),
]

apps/servicos/models.py
import datetime
from django.db import models
from geral.models import Oficina, Mecanico


# Create your models here.

class Servico(models.Model):
    oficina = models.ForeignKey(Oficina, verbose_name='Oficina', on_delete=models.CASCADE, null=True)
    nome = models.CharField(verbose_name='Nome', max_length=70)
    descricao = models.TextField(verbose_name='Descrição', blank=True, null=True)
    valor = models.DecimalField(verbose_name='Valor R$', max_digits=19, decimal_places=2)
    comissao = models.DecimalField(verbose_name='Comissão R$', max_digits=19, decimal_places=2)

    def __str__(self) -> str:
        return self.nome
    
    class Meta:
        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'
        ordering = ['nome']


class OrdemServico(models.Model):
    oficina = models.ForeignKey(Oficina, verbose_name='Oficina', on_delete=models.CASCADE)
    mecanico = models.ForeignKey(Mecanico, verbose_name='Mecânico', on_delete=models.SET_NULL, null=True)
    cliente = models.CharField(verbose_name='Cliente', max_length=100)
    veiculo = models.CharField(verbose_name='Veículo', max_length=100, help_text='Ex: Moto Fan 160')
    placa = models.CharField(verbose_name='Placa', max_length=8, help_text='Ex: AAA-0000')
    previsao = models.DateField(verbose_name='Previsão', default=datetime.datetime.now)
    data_entrada = models.DateTimeField(verbose_name='Data/Hora Entrada', auto_now=True)
    codigo = models.PositiveIntegerField(verbose_name='Código OS', unique=True)
    servico = models.ManyToManyField(Servico, verbose_name='Serviços', related_name='os')

    def __str__(self) -> str:
        return self.oficina.nome
    
    class Meta:
        verbose_name = 'Ordem de Serviço'
        verbose_name_plural = 'Ordem de Serviços'
        ordering = ['data_entrada']

apps/servicos/forms.py
from django import forms

from .models import Servico, OrdemServico


class ServicoForm(forms.ModelForm):
    class Meta:
        model = Servico
        exclude = ['oficina']

class OrdemServicoForm(forms.ModelForm):
    class Meta:
        model = OrdemServico
        exclude = ['oficina']

apps/servicos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import ServicoForm, OrdemServicoForm

from .models import Servico, OrdemServico
from geral.models import Oficina


@login_required
def lista_servicos(request):
    template_name = 'servicos/lista_servicos.html'
    oficina = Oficina.objects.filter(usuario=request.user).first()
    servicos = Servico.objects.filter(oficina=oficina)
    context = {
        'servicos': servicos,
    }
    return render(request, template_name, context)


@login_required
def novo_servico(request):
    template_name = 'servicos/novo_servico.html'
    context = {}
    if request.method == 'POST':
        form = ServicoForm(request.POST)
        oficina = Oficina.objects.filter(usuario=request.user).first()
        if form.is_valid():
            sf = form.save(commit=False)
            sf.oficina = oficina
            sf.save()
            messages.success(request, 'Servico adicionado com sucesso')
            return redirect('servicos:lista_servicos')
    form = ServicoForm()
    context['form'] = form
    return render(request, template_name, context)


@login_required
def editar_servico(request, pk):
    template_name = 'servicos/novo_servico.html'
    context = {}
    servico = get_object_or_404(Servico, pk=pk)
    if request.method == 'POST':
        form = ServicoForm(data=request.POST, instance=servico)
        if form.is_valid():
            form.save()
            messages.success(request, 'Serviço atualizado com sucesso')
            return redirect('servicos:lista_servicos')  # Corrected URL name
    else:
        form = ServicoForm(instance=servico)
    context['form'] = form
    return render(request, template_name, context)


# ***************************************** Ordem de Serviços *****************************************
@login_required
def criar_ordem_servico(request):
    template_name = 'servicos/criar_ordem_servico.html'
    context = {}
    oficina = get_object_or_404(Oficina, usuario=request.user)
    if request.method == 'POST':
        form = OrdemServicoForm(request.POST)
        if form.is_valid():
            osf = form.save(commit=False)
            osf.oficina = oficina
            osf.save()
            messages.success(request, 'Ordem cadastrado com sucesso')
            return redirect('servicos:lista_ordem_servico')
    form = OrdemServicoForm()
    context['form'] = form
    return render(request, template_name, context)


@login_required
def lista_ordem_servico(request):
    template_name = 'servicos/lista_ordem_servico.html'
    oficina = get_object_or_404(Oficina, usuario=request.user)
    ordens_servicos = OrdemServico.objects.filter(oficina=oficina)
    context = {
        'ordens_servicos': ordens_servicos
    }
    return render(request, template_name, context)


@login_required
def editar_ordem_servico(request, pk):
    template_name = 'servicos/criar_ordem_servico.html'
    context = {}
    ordem_servico = get_object_or_404(OrdemServico, pk=pk)
    if request.method == 'POST':
        form = OrdemServicoForm(data=request.POST, instance=ordem_servico)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ordem de servico atualizado com sucesso!')
            return redirect('servicos:lista_ordem_servico')  # Corrected URL name
    else:
        form = OrdemServicoForm(instance=ordem_servico)
    context['form'] = form
    return render(request, template_name, context)

templates/servicos/criar_ordem_servico.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block titulo %}

	 Criar Ordem de Serviço | {{ block.super }}

{% endblock titulo %}


{% block main %}
    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="{{ form.mecanico.id_for_label }}" class="form-label">{{ form.mecanico.label }}</label>
            {% render_field form.mecanico class='form-control' placeholder='Escolha o Mecanico....' %}
        </div>  
    
         <div class="mb-3">
            <label for="{{ form.cliente.id_for_label }}" class="form-label">{{ form.cliente.label }}</label>
            {% render_field form.cliente class='form-control' placeholder='....' %}
        </div>
        
        <div class="mb-3">
            <label for="{{ form.veiculo.id_for_label }}" class="form-label">{{ form.veiculo.label }}</label>
            {% render_field form.veiculo class='form-control' placeholder='....' %}        
        </div>
        
        <div class="mb-3">
            <label for="{{ form.placa.id_for_label }}" class="form-label">{{ form.placa.label }}</label>
            {% render_field form.placa class='form-control' placeholder='....' %}
        </div>
        <div class="mb-3">
            <label for="{{ form.previsao.id_for_label }}" class="form-label">{{ form.previsao.label }}</label>
            {% render_field form.previsao class='form-control' placeholder='....' %}
        </div>
        <div class="mb-3">
            <label for="{{ form.data_entrada.id_for_label }}" class="form-label">{{ form.data_entrada.label }}</label>
            {% render_field form.data_entrada class='form-control' placeholder='....' %}
        </div>
        <div class="mb-3">
            <label for="{{ form.codigo.id_for_label }}" class="form-label">{{ form.codigo.label }}</label>
            {% render_field form.codigo class='form-control' placeholder='....' %}
        </div>
        <div class="mb-3">
            <label for="{{ form.servico.id_for_label }}" class="form-label">{{ form.servico.label }}</label>
            {% render_field form.servico class='form-control' placeholder='....' %}
        </div>
    
        <button type="submit" class="btn btn-primary"> Adcionar </button>
        <a "{% url 'servicos:lista_servicos' %}" class="btn btn-outline-secondary">Cancelar</a>
    </form>
{% endblock main %}

templates/servicos/lista_ordem_servico.html
{% extends 'base.html' %}

{% block titulo %}
	Ordem de Serviços |{{ block.super }}
{% endblock titulo %}

{% block main %}
    {% include 'utils/messages.html' %}
     <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Cliente</th>
          <th scope="col">Placa</th>
          <th scope="col">Previsão</th>
          <th scope="col">Serviços</th>
          <th scope="col" colspan="2">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for os in ordens_servicos %}
            <tr>
                <th scope="row">{{ os.id }}</th>
                <td>{{ os.cliente }}</td>
                <td>{{ os.placa }}</td>
                <td>{{ os.precisao }}</td>
                <td>{{ os.servico }}</td>                
                <td><a href="{% url 'servicos:editar_ordem_servico' os.id %}" class="btn btn-outline-info btn-sm">Editar <i class="ph ph-recycle"></i> </a></td>
            </tr>
        {% endfor %}       
      </tbody>
        
    </table>
    <a href="{% url 'servicos:criar_ordem_servico' %}" class="btn btn-primary">Criar OS</a>

{% endblock main %}

templates/servicos/lista_servico.html
{% extends 'base.html' %}

{% block titulo %}
	Serviços |{{ block.super }}
{% endblock titulo %}

{% block main %}
    {% include 'utils/messages.html' %}
     <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nome</th>
          <th scope="col">Descrição</th>
          <th scope="col">Valor</th>
          <th scope="col">comissao</th>
          <th scope="col" colspan="2">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for servico in servicos %}
            <tr>
                <th scope="row">{{ servico.id }}</th>
                <td>{{ servico.nome }}</td>
                <td>{{ servico.descricao }}</td>
                <td>{{ servico.valor }}</td>
                <td>{{ servico.comissao }}</td>                
                <td><a href="{% url 'servicos:editar_servico' servico.id %}" class="btn btn-outline-info btn-sm">Editar <i class="ph ph-recycle"></i> </a>
                    
                </td>
        </tr>
        {% endfor %}       
      </tbody>
        
    </table>
    <a href="{% url 'servicos:novo_servico' %}" class="btn btn-primary">Novo</a>

{% endblock main %}

templates/servicos/lista_servicos.html
{% extends 'base.html' %}

{% block titulo %}
	Serviços |{{ block.super }}
{% endblock titulo %}

{% block main %}
    {% include 'utils/messages.html' %}
     <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Nome</th>
          <th scope="col">Descrição</th>
          <th scope="col">Valor</th>
          <th scope="col">comissao</th>
          <th scope="col" colspan="2">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for servico in servicos %}
            <tr>
                <th scope="row">{{ servico.id }}</th>
                <td>{{ servico.nome }}</td>
                <td>{{ servico.descricao }}</td>
                <td>{{ servico.valor }}</td>
                <td>{{ servico.comissao }}</td>                
                <td><a href="{% url 'servicos:editar_servico' servico.id %}" class="btn btn-outline-info btn-sm">Editar <i class="ph ph-recycle"></i> </a>
                    
                </td>
        </tr>
        {% endfor %}       
      </tbody>
        
    </table>
    <a href="{% url 'servicos:novo_servico' %}" class="btn btn-primary">Novo</a>

{% endblock main %}

templates/servicos/novo_servico.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block titulo %}

	 Servico | {{ block.super }}

{% endblock titulo %}


{% block main %}
    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="{{ form.nome.id_for_label }}" class="form-label">{{ form.nome.label }}</label>
            {% render_field form.nome class='form-control' placeholder='Digite o Serviço a ser feito....' %}
        </div>  
    
         <div class="mb-3">
            <label for="{{ form.descricao.id_for_label }}" class="form-label">{{ form.descricao.label }}</label>
            {% render_field form.descricao class='form-control' placeholder='Digite a descrição do serviço....' %}
        </div>
        
        <div class="mb-3">
            <label for="{{ form.valor.id_for_label }}" class="form-label">{{ form.valor.label }}</label>
            {% render_field form.valor class='form-control' placeholder='Digite o valor do serviço....' %}        
        </div>
        
        <div class="mb-3">
            <label for="{{ form.comissao.id_for_label }}" class="form-label">{{ form.comissao.label }}</label>
            {% render_field form.comissao class='form-control' placeholder='Digite a comissão....' %}
        </div>
    
        <button type="submit" class="btn btn-primary"> Adcionar </button>
        <a "{% url 'servicos:lista_servicos' %}" class="btn btn-outline-secondary">Cancelar</a>
    </form>
{% endblock main %}